# =============================================================================
# Sexism Detection — Logistic Regression with TF-IDF
# Training: vectorize, fit, evaluate, persist artifacts and probabilities
# EDOS dataset (SemEval-2023 Task 10)
#
# Security note: .joblib files execute Python code when loaded. Only load
# artifacts generated by this repository.
# =============================================================================

# -----------------------------------------------------------------------------
# Imports
# -----------------------------------------------------------------------------
import os
from pathlib import Path

import joblib
import numpy as np
import polars as pl
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    roc_auc_score,
)


# -----------------------------------------------------------------------------
# Base path resolution
# -----------------------------------------------------------------------------
try:
    _base = Path(__file__).resolve().parent.parent.parent
except NameError:
    _base = Path(os.getcwd())


# -----------------------------------------------------------------------------
# 1. Load processed data
# -----------------------------------------------------------------------------
processed_dir = _base / "data" / "processed"

train_df = pl.read_parquet(processed_dir / "train.parquet")
dev_df = pl.read_parquet(processed_dir / "dev.parquet")
test_df = pl.read_parquet(processed_dir / "test.parquet")


# -----------------------------------------------------------------------------
# 2. Feature / target separation
# -----------------------------------------------------------------------------
X_train = train_df["text"]
y_train = train_df["label"]

X_dev = dev_df["text"]
y_dev = dev_df["label"]

X_test = test_df["text"]
y_test = test_df["label"]

print(X_train.shape, y_train.shape)
print(X_dev.shape, y_dev.shape)
print(X_test.shape, y_test.shape)


# -----------------------------------------------------------------------------
# 3. TF-IDF vectorization
# Default configuration. Experimentally, the default vectorizer outperforms
# every tuned configuration on the test set (see the tuning block below) —
# tuning overfit to the dev set. The vocabulary is fitted on the training set
# only, then applied to dev and test. Fitting on unseen data would introduce
# data leakage.
# -----------------------------------------------------------------------------
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_dev_tfidf = vectorizer.transform(X_dev)
X_test_tfidf = vectorizer.transform(X_test)

print(X_train_tfidf.shape)
print(X_dev_tfidf.shape)
print(X_test_tfidf.shape)


# -----------------------------------------------------------------------------
# 4. Baseline model
# class_weight="balanced" compensates the 76/24 class imbalance confirmed in EDA.
# -----------------------------------------------------------------------------
model = LogisticRegression(class_weight="balanced", max_iter=1000, random_state=42)
model.fit(X_train_tfidf, y_train)

print("Model trained")


# -----------------------------------------------------------------------------
# 5. Baseline evaluation on test set
# Accuracy alone is misleading under class imbalance: precision, recall, F1 and
# ROC-AUC are reported per class.
# Expected results: F1 (sexist) = 0.63, macro F1 = 0.74, ROC-AUC = 0.847.
# -----------------------------------------------------------------------------
y_pred = model.predict(X_test_tfidf)

print(classification_report(y_test, y_pred, target_names=["not sexist", "sexist"]))
print(confusion_matrix(y_test, y_pred))

y_proba = model.predict_proba(X_test_tfidf)[:, 1]
print("ROC-AUC:", roc_auc_score(y_test, y_proba))


# -----------------------------------------------------------------------------
# 6. Hyperparameter tuning (disabled)
# Kept as experimental evidence. Enable RUN_TUNING to reproduce.
#
# Vectorizer sweep results (ngram_range, min_df, vocab size, F1 sexist on dev):
#   (1,1)  min_df=1  vocab=20,964   F1=0.5942
#   (1,2)  min_df=3  vocab=22,929   F1=0.6157
#   (1,3)  min_df=1  vocab=427,511  F1=0.5967
#   (1,3)  min_df=2  vocab=55,555   F1=0.6284
#   (1,3)  min_df=3  vocab=28,351   F1=0.6208
#   (1,3)  min_df=5  vocab=14,265   F1=0.6080
#   (1,4)  min_df=2  vocab=58,558   F1=0.6279
#   (1,5)  min_df=2  vocab=59,094   F1=0.6265
#
# Tuned model on test: F1 (sexist) = 0.61, macro F1 = 0.73, ROC-AUC = 0.845.
# Worse than the baseline — overfitting to the validation set.
# -----------------------------------------------------------------------------
RUN_TUNING = False

if RUN_TUNING:
    # -------------------------------------------------------------------
    # 6a. Hyperparameter tuning — C
    # Each candidate is evaluated on the dev set. The test set remains
    # untouched until the final evaluation.
    # -------------------------------------------------------------------
    for C in [0.01, 0.1, 1, 10, 100]:
        tuning_model = LogisticRegression(C=C, class_weight="balanced", max_iter=1000)
        tuning_model.fit(X_train_tfidf, y_train)

        y_dev_pred = tuning_model.predict(X_dev_tfidf)
        dev_f1 = f1_score(y_dev, y_dev_pred)

        print(f"C={C}: F1 (sexist) = {dev_f1:.4f}")

    # -------------------------------------------------------------------
    # 6b. Hyperparameter tuning — vectorizer
    # Changing the vectorizer requires re-fitting it and re-transforming
    # the data, not just re-training the model.
    # -------------------------------------------------------------------
    configs = [
        {"ngram_range": (1, 1), "min_df": 1},
        {"ngram_range": (1, 2), "min_df": 3},
        {"ngram_range": (1, 3), "min_df": 2},
        {"ngram_range": (1, 3), "min_df": 5},
        {"ngram_range": (1, 3), "min_df": 2},
        {"ngram_range": (1, 4), "min_df": 2},
        {"ngram_range": (1, 5), "min_df": 2},
    ]

    for config in configs:
        tuning_vectorizer = TfidfVectorizer(**config)

        X_train_tuning = tuning_vectorizer.fit_transform(X_train)
        X_dev_tuning = tuning_vectorizer.transform(X_dev)

        tuning_model = LogisticRegression(C=1, class_weight="balanced", max_iter=1000)
        tuning_model.fit(X_train_tuning, y_train)

        y_dev_pred = tuning_model.predict(X_dev_tuning)
        dev_f1 = f1_score(y_dev, y_dev_pred)

        vocab_size = X_train_tuning.shape[1]
        print(f"{config} -> vocab={vocab_size:>7} | F1 (sexist) = {dev_f1:.4f}")

    # -------------------------------------------------------------------
    # 6c. Re-tuning C on the winning vectorizer
    # -------------------------------------------------------------------
    best_vectorizer = TfidfVectorizer(ngram_range=(1, 3), min_df=2)

    X_train_best = best_vectorizer.fit_transform(X_train)
    X_dev_best = best_vectorizer.transform(X_dev)

    for C in [0.1, 0.5, 1, 2, 5, 10]:
        tuning_model = LogisticRegression(C=C, class_weight="balanced", max_iter=1000)
        tuning_model.fit(X_train_best, y_train)

        y_dev_pred = tuning_model.predict(X_dev_best)
        dev_f1 = f1_score(y_dev, y_dev_pred)

        print(f"C={C}: F1 (sexist) = {dev_f1:.4f}")

    # -------------------------------------------------------------------
    # 6d. Tuned model — evaluated once on the test set
    # Configuration selected via dev-set grid search (sections 6a-6c).
    # Result: underperforms the baseline on test. Kept as evidence of the
    # validation-set overfitting phenomenon.
    # -------------------------------------------------------------------
    tuned_model = LogisticRegression(
        C=1, class_weight="balanced", max_iter=1000, random_state=42
    )
    tuned_model.fit(X_train_best, y_train)

    X_test_best = best_vectorizer.transform(X_test)
    y_test_pred = tuned_model.predict(X_test_best)
    y_test_proba = tuned_model.predict_proba(X_test_best)[:, 1]

    print("\n=== TUNED MODEL — TEST SET ===")
    print(classification_report(y_test, y_test_pred, target_names=["not sexist", "sexist"]))
    print(confusion_matrix(y_test, y_test_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_test_proba))


# -----------------------------------------------------------------------------
# 7. Save artifacts
# The vectorizer holds the learned vocabulary, the model holds the learned
# weights. Probabilities and labels are from the baseline model and are saved
# for the ensemble stage.
# -----------------------------------------------------------------------------
artifacts_dir = _base / "models" / "logistic_regression"
results_dir = artifacts_dir / "results"
results_dir.mkdir(parents=True, exist_ok=True)

joblib.dump(vectorizer, artifacts_dir / "vectorizer.joblib")
joblib.dump(model, artifacts_dir / "model.joblib")

dev_proba = model.predict_proba(X_dev_tfidf)[:, 1]
test_proba = model.predict_proba(X_test_tfidf)[:, 1]

np.save(results_dir / "dev_probs.npy", dev_proba)
np.save(results_dir / "test_probs.npy", test_proba)
np.save(results_dir / "dev_labels.npy", y_dev.to_numpy())
np.save(results_dir / "test_labels.npy", y_test.to_numpy())

print("Artifacts saved")
